### ISSUE TITLE
ItemStack's stack size is sometimes incorrect

### ISSUE THREAD

**Issue by harrynull** [D-Cysteine/nesql-exporter#2]
Thank you for making this mod and the exported data looks great for the most parts. I made a simple [GraphQL backend](https://github.com/harrynull/NEIGraphQL) and a simple [frontend](https://github.com/harrynull/webnei) (hosted [here](https://webnei.harrynull.tech/)). I do however in the development process notice that the stack size of some inputs is incorrect.
Taking the ZPM Field Generator from GTNH as an example.

![image](https://user-images.githubusercontent.com/7413706/220176904-4bed21dc-bf4f-4a4b-a282-ff8a2f79b58b.png)
![image](https://user-images.githubusercontent.com/7413706/220176648-fddcd98b-25ef-4361-bf9b-884d6e9c641d.png)

Fine Ruridit Wire and HSS-S Plate has incorrect stack size.

**Comment by D-Cysteine** [comment]
Oops, thanks for catching this! Should be fixed by https://github.com/D-Cysteine/nesql-exporter/commit/e026e2f6a88aa3d500f42dc5c51c14f78fb54cd6.

Wow, that UI looks great! I hadn't heard of GraphQL before, so thanks for pointing me to that as well!
In case you haven't seen it, and its code is helpful to you, I do have a UI here too: https://github.com/D-Cysteine/nesql-server
What you have is definitely way more usable though
